name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Install Conan dependencies
      shell: bash
      run: |
        sudo apt-get install python3-pip
        pip3 install conan
        conan profile detect --force
        conan install . --build=missing -if=build

    - name: Compile
      shell: bash
      run: |
        SRC_FOLDER=$(pwd)/src

        mkdir -p build && cd build
        echo "Running command: cmake -DRUN_COVERAGE=1 .. && make -j2"
        cmake -DRUN_COVERAGE=1 -DENABLE_CJSON_TEST=OFF .. && make -j2