name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip 
        pip3 install conan

    - name: Install Conan dependencies
      shell: bash
      run: |
        conan profile detect --force
        conan install . --build=missing --output-folder=build
        ls -l build

    - name: Compile
      shell: bash
      run: |
        mkdir -p build && cd build
        echo "Running command: cmake -DRUN_COVERAGE=1 -DENABLE_CJSON_TEST=OFF .. && make -j2"
        cmake -DCMAKE_TOOLCHAIN_FILE=build/build/Release/generators/conan_toolchain.cmake -DRUN_COVERAGE=1 -DENABLE_CJSON_TEST=OFF ..
        make -j2
