name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip 
        pip3 install conan

    - name: Install Conan dependencies
      shell: bash
      run: |
        conan profile detect --force
        cp ~/.conan2/profiles/default ~/.conan2/profiles/debug
        sed -i 's/build_type=Release/build_type=Debug/g' ~/.conan2/profiles/debug
        cat ~/.conan2/profiles/debug
        conan install . --build=missing --output-folder=build --profile=debug


        

    - name: Compile
      shell: bash
      run: |
        mkdir -p build && cd build
        echo "Running command: cmake -DRUN_COVERAGE=1 -DENABLE_CJSON_TEST=OFF .. && make -j2"
        cmake .. -DCMAKE_TOOLCHAIN_FILE=./conan_toolchain.cmake -DRUN_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug
        make -j2

